### ISSUE TITLE
Link to the full installer is not mentioned 

### ISSUE THREAD

**Issue by TrutzS** [MicrosoftDocs/data-integration#9] opened 2019-09-20 15:14 UTC
The link to the full installer https://www.microsoft.com/en-us/download/details.aspx?id=53127 is not mentioned here, which would remove the requirement for port 80.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c51a10c-d90c-7690-0979-cd8ce37234c8
* Version Independent ID: 2da65f4c-f128-40b8-1a2b-5ae72c4252d6
* Content: [Install an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-install)
* Content Source: [data-integration/gateway/service-gateway-install.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-install.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateway**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by DougKlopfenstein** [comment] 2020-03-26 22:03
Removing because it is a duplicate of https://github.com/MicrosoftDocs/data-integration/issues/8.

**Closed by DougKlopfenstein** 2020-03-26 22:03 UTC
Labels: duplicate
