### ISSUE TITLE
Gateway version is not showing correctly in puwer platform admin

### ISSUE THREAD

**Issue by albertocastro365** [MicrosoftDocs/data-integration#83] opened 2020-11-28 20:33 UTC
Hi,
I have two cluster of gateways, all in the latest vertsion, november 2020, but in platform admin, the secondary nodes of the both clusters not showing the correct version.:

![image](https://user-images.githubusercontent.com/57954993/100525427-1bd00980-31c1-11eb-98a0-f57c686abf72.png)

What is the reason of this behaviour?

**Comment by ZdenekSoldan** [comment] 2021-01-08 07:26
The same issue is in our tenant for almost a year. The wrong version can be seen in the Power Platform admin portal and also in Power BI manage gateways admin portal. The only solution which works for me is to sign in into the On-Premises data gateway service locally on each server of the cluster. After that, the current version is successfully transferred into the cloud environment.

**Comment by aslr1** [comment] 2022-10-28 02:31
I can confirm this issue is still present with gateway version 3000.146.10 (October 2022).

The fix by @ZdenekSoldan worked, thanks.

**Comment by zeroxiga** [comment] 2023-07-14 04:21
Looks like the version only get updated when it gets restarted and sign-in in the on-premises data gateway app. By restarting the hosting server, and/or restart the service via services msc do not update the version.

**Comment by DougKlopfenstein** [comment] 2023-09-27 18:21
Hi @albertocastro365 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, we can help redirect you to the right support channel to get an answer to your question: [Get Help + Support](https://learn.microsoft.com/power-platform/admin/get-help-support). Because this issue does not relate to documentation, we are closing this issue.

**Closed by DougKlopfenstein** 2023-09-27 18:21 UTC
Labels: Pri3, product-feedback
